# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62ookings.proto\"3\n\x07\x42ooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.Schedule\"(\n\x08Schedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x1b\n\x0b\x44\x61teBooking\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyBooking\"\x14\n\x04User\x12\x0c\n\x04user\x18\x01 \x01(\t\"R\n\x0bUserBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x01(\t\x12\"\n\x0c\x64\x61te_booking\x18\x03 \x01(\x0b\x32\x0c.DateBooking2\x90\x01\n\x08\x42ookings\x12-\n\x0eGetAllBookings\x12\r.EmptyBooking\x1a\x08.Booking\"\x00\x30\x01\x12\'\n\x10GetBookingByUser\x12\x05.User\x1a\x08.Booking\"\x00\x30\x01\x12,\n\x10\x41\x64\x64\x42ookingByUser\x12\x0c.UserBooking\x1a\x08.Booking\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKING']._serialized_start=18
  _globals['_BOOKING']._serialized_end=69
  _globals['_SCHEDULE']._serialized_start=71
  _globals['_SCHEDULE']._serialized_end=111
  _globals['_DATEBOOKING']._serialized_start=113
  _globals['_DATEBOOKING']._serialized_end=140
  _globals['_EMPTYBOOKING']._serialized_start=142
  _globals['_EMPTYBOOKING']._serialized_end=156
  _globals['_USER']._serialized_start=158
  _globals['_USER']._serialized_end=178
  _globals['_USERBOOKING']._serialized_start=180
  _globals['_USERBOOKING']._serialized_end=262
  _globals['_BOOKINGS']._serialized_start=265
  _globals['_BOOKINGS']._serialized_end=409
# @@protoc_insertion_point(module_scope)
