# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bookings_pb2 as bookings__pb2


class BookingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllBookings = channel.unary_stream(
                '/Bookings/GetAllBookings',
                request_serializer=bookings__pb2.EmptyBooking.SerializeToString,
                response_deserializer=bookings__pb2.Booking.FromString,
                )
        self.GetBookingByUser = channel.unary_stream(
                '/Bookings/GetBookingByUser',
                request_serializer=bookings__pb2.User.SerializeToString,
                response_deserializer=bookings__pb2.Booking.FromString,
                )
        self.AddBookingByUser = channel.unary_unary(
                '/Bookings/AddBookingByUser',
                request_serializer=bookings__pb2.UserBooking.SerializeToString,
                response_deserializer=bookings__pb2.Booking.FromString,
                )


class BookingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookingByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=bookings__pb2.EmptyBooking.FromString,
                    response_serializer=bookings__pb2.Booking.SerializeToString,
            ),
            'GetBookingByUser': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBookingByUser,
                    request_deserializer=bookings__pb2.User.FromString,
                    response_serializer=bookings__pb2.Booking.SerializeToString,
            ),
            'AddBookingByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookingByUser,
                    request_deserializer=bookings__pb2.UserBooking.FromString,
                    response_serializer=bookings__pb2.Booking.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bookings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bookings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Bookings/GetAllBookings',
            bookings__pb2.EmptyBooking.SerializeToString,
            bookings__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookingByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Bookings/GetBookingByUser',
            bookings__pb2.User.SerializeToString,
            bookings__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBookingByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bookings/AddBookingByUser',
            bookings__pb2.UserBooking.SerializeToString,
            bookings__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
