# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import times_pb2 as times__pb2


class TimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllShowtimes = channel.unary_stream(
                '/Time/GetAllShowtimes',
                request_serializer=times__pb2.Empty.SerializeToString,
                response_deserializer=times__pb2.ShowTime.FromString,
                )
        self.GetMmoviesBydate = channel.unary_unary(
                '/Time/GetMmoviesBydate',
                request_serializer=times__pb2.Date.SerializeToString,
                response_deserializer=times__pb2.ShowTime.FromString,
                )


class TimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllShowtimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMmoviesBydate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllShowtimes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllShowtimes,
                    request_deserializer=times__pb2.Empty.FromString,
                    response_serializer=times__pb2.ShowTime.SerializeToString,
            ),
            'GetMmoviesBydate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMmoviesBydate,
                    request_deserializer=times__pb2.Date.FromString,
                    response_serializer=times__pb2.ShowTime.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Time', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Time(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllShowtimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Time/GetAllShowtimes',
            times__pb2.Empty.SerializeToString,
            times__pb2.ShowTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMmoviesBydate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Time/GetMmoviesBydate',
            times__pb2.Date.SerializeToString,
            times__pb2.ShowTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
